//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeCityInfo
    {
        public long Id { get; set; }
        public string City { get; set; }
        public decimal Temperature { get; set; }
        public string TempUnits { get; set; }
        public string Description { get; set; }
        public long Pressure { get; set; }
        public long Humidity { get; set; }
        public decimal WindSpeed { get; set; }
        public string Time { get; set; }
    }
}
